language: go

go: 1.6

install:
  # We override the install phase to avoid the default "go get ... / godep restore"
  # because we only want the deps from Godeps
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
  - go vet ./...

script:
  - go test -v ./...
  - go build
